version: '3.8'

services:
  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: [ "/scripts/start-namenode.sh" ]
    networks:
      - hadoop-net

  datanode1:
    build: .
    container_name: datanode1
    hostname: datanode1
    ports:
      - "9864:9864"
    environment:
      HDFS_DATANODE_OPTS: "-Ddfs.datanode.http.address=0.0.0.0:9864 -Ddfs.datanode.hostname=datanode1"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: [ "/scripts/start-datanode.sh" ]
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode2:
    build: .
    container_name: datanode2
    hostname: datanode2
    ports:
      - "9865:9865"
    environment:
      HDFS_DATANODE_OPTS: "-Ddfs.datanode.http.address=0.0.0.0:9865 -Ddfs.datanode.hostname=datanode2"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: [ "/scripts/start-datanode.sh" ]
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode3:
    build: .
    container_name: datanode3
    hostname: datanode3
    ports:
      - "9866:9866"
    environment:
      HDFS_DATANODE_OPTS: "-Ddfs.datanode.http.address=0.0.0.0:9866 -Ddfs.datanode.hostname=datanode3"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: [ "/scripts/start-datanode.sh" ]
    depends_on:
      - namenode
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge
